name: build-windows
# on:
#   schedule:
#     - cron: '0 0 * * *'
on:
#  push:
#    branches:
#      - master
 workflow_dispatch: # 添加这个触发器
jobs:
  build:
    name: Build
    runs-on: windows-2022
    strategy:
      matrix:
        version: [6.8.*]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: ${{ github.workspace }}
          version: ${{ matrix.version }}
          target: desktop
          arch: win64_msvc2022_64
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}' -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ../
          nmake
          
      - name: Save Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-software
          path: ./build/assets/xTools  # 替换为生成的文件路径
